"""Streamlit UI for CV Reviewer."""
from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any, Dict

import streamlit as st

from app.feedback import generate_feedback, generate_overall_summary
from app.scorer import grade_for, score_cv
from app.role_detector import VALID_ROLES, detect_role_from_sections
from app.rubric_registry import RUBRIC_ROLES, load_rubric
from app.health import (
    check_ollama_health,
    health_summary_text,
    clear_health_cache,
    HEALTH_OK,
    HEALTH_OFFLINE,
    HEALTH_MODEL_MISSING,
)
# --------------------------------------------------------------------------- #
# Page setup
# --------------------------------------------------------------------------- #
st.set_page_config(
    page_title="CV Reviewer · Local RAG",
    page_icon="📄",
    layout="wide",
)

st.title("📄 CV Reviewer — Local RAG")
st.caption(
    "Upload a CV (PDF or DOCX) and optionally a Job Description. "
    "Scoring is rule-based and deterministic. "
    "Narrative feedback is generated by local Ollama (qwen2.5:3b) "
    "grounded in an ATS rubric via RAG."
)

# --------------------------------------------------------------------------- #
# Sidebar
# --------------------------------------------------------------------------- #
with st.sidebar:
    # --- Ollama health (C2) ----------------------------------------------- #
    # Probe the local Ollama server and show a clear status pill so the
    # recruiter knows whether the app is operational. A "Refresh" button
    # clears the lru_cache so users can re-probe after starting Ollama
    # without restarting the Streamlit session.
    st.header("🔌 Ollama status")
    health = check_ollama_health()
    summary, code = health_summary_text(health)
    if code == HEALTH_OK:
        st.success(summary)
    elif code == HEALTH_OFFLINE:
        st.error(summary)
    else:  # HEALTH_MODEL_MISSING
        st.warning(summary)
        with st.expander("How to fix", expanded=False):
            st.markdown(
                "```bash\n"
                "# Start Ollama\n"
                "ollama serve\n\n"
                "# Pull the missing model(s) listed above\n"
                "ollama pull qwen2.5:3b\n"
                "ollama pull nomic-embed-text\n"
                "```"
            )
            if st.button("🔄 Refresh", key="ollama_refresh"):
                clear_health_cache()
                st.rerun()

    st.divider()
    st.header("How it works")
    st.markdown(
        """
        1. **Parse** your CV by section
        2. **Score** each section with deterministic heuristics
        3. *(Optional)* Match against a Job Description for gap analysis
        4. **Retrieve** relevant ATS rules from a vector KB
        5. **Generate** per-section feedback via local LLM

        Knowledge base: 10 ATS rubric rules.
        Embeddings: `nomic-embed-text` (Ollama).
        LLM: `qwen2.5:3b` (Ollama).
        """
    )
    st.divider()

    # Language preference (P1.4): 'auto' detects from CV, override available.
    language_pref = st.selectbox(
        "🌐 Feedback language",
        options=["auto", "en", "id"],
        index=0,
        help=(
            "Auto detects Indonesian vs English from your CV. "
            "Override to force a specific language for the LLM feedback."
        ),
    )

    st.divider()
    st.header("Role-specific rubric")

    # Role selector (P2.0 — task #5): 'auto' lets the detector pick, or
    # force a specific role. Default to 'auto' so first-time users get
    # the smart default; advanced users can override.
    role_pref = st.selectbox(
        "🎯 Target role",
        options=["auto", *RUBRIC_ROLES],
        index=0,
        help=(
            "Auto detects from your CV's Skills + Summary text. "
            "Override to force a specific role rubric. "
            "Each role weights sections differently — PM prioritizes "
            "impact bullets, SWE/Data prioritize named tools and metrics."
        ),
    )
    if role_pref != "auto":
        st.caption(f"Rubric: **{role_pref}** (manual override)")

    st.caption("v0.4 · ID/EN bilingual · PDF + DOCX · JD match · role-specific rubrics (swe/data/pm)")


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def render_score_card(report) -> None:
    col1, col2, col3, col4 = st.columns([2, 1, 1, 1.2])
    with col1:
        st.metric("Overall Score", f"{report.overall} / 10")
    with col2:
        st.metric("Grade", report.grade)
    with col3:
        weak_count = sum(len(s.issues) for s in report.sections.values())
        st.metric("Issues Found", weak_count)
    with col4:
        # Role badge with confidence indicator. If confidence is low
        # (< 0.5), the badge gets an asterisk to signal "auto-detected,
        # you might want to override in the sidebar".
        role_emoji = {
            "general": "📋",
            "swe": "💻",
            "data": "📊",
            "pm": "🎯",
        }.get(report.role, "📋")
        role_label = f"{role_emoji} {report.role.upper()}"
        if report.role_confidence < 0.5:
            role_label += " *"
        st.metric(
            "Role rubric",
            role_label,
            f"conf {report.role_confidence:.0%}",
            delta_color="off",
        )

    st.progress(min(report.overall / 10, 1.0))

    # Confidence asterisk hint when role is auto-detected at low confidence.
    if report.role_confidence < 0.5:
        st.caption(
            "⚠️ *Auto-detected role confidence is low. Override the role "
            "in the sidebar if this looks wrong.*"
        )


def render_section(name: str, section, feedback_text: str | None) -> None:
    display_name = name.replace("_", " ").title()
    color = (
        "🟢" if section.score >= 8
        else "🟡" if section.score >= 6
        else "🟠" if section.score >= 4
        else "🔴"
    )
    with st.expander(f"{color} **{display_name}** — {section.score}/10", expanded=(section.score < 6)):
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**✅ Strengths**")
            if section.evidence:
                for e in section.evidence:
                    st.markdown(f"- {e}")
            else:
                st.caption("(none detected)")
        with c2:
            st.markdown("**⚠️ Issues**")
            if section.issues:
                for i in section.issues:
                    st.markdown(f"- {i}")
            else:
                st.caption("(no issues — clean)")
        if feedback_text:
            st.divider()
            st.markdown("**🤖 Reviewer feedback**")
            st.markdown(feedback_text)


def render_jd_match(jd_match) -> None:
    """Render the JD match panel: required coverage, gaps, nice-to-haves."""
    if jd_match is None:
        return

    st.divider()
    st.subheader("🎯 Job Description Match")

    if jd_match.required_total == 0 and jd_match.nice_total == 0:
        st.warning(
            "Could not extract skills from the Job Description. "
            "Try including a 'Requirements' or 'Qualifications' section."
        )
        return

    # Headline metrics
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.metric("JD Score", f"{jd_match.overall_jd_score} / 10")
    with c2:
        st.metric(
            "Required coverage",
            f"{jd_match.required_match_ratio:.0%}",
            f"{jd_match.required_matched} / {jd_match.required_total}",
        )
    with c3:
        st.metric(
            "Nice-to-have",
            f"{jd_match.nice_match_ratio:.0%}",
            f"{jd_match.nice_matched} / {jd_match.nice_total}" if jd_match.nice_total else "—",
        )
    with c4:
        if jd_match.years_required > 0:
            st.metric(
                "Years",
                f"+{jd_match.years_gap}",
                f"need {jd_match.years_required}+",
                delta_color="inverse",
            )
        else:
            role_label = "✅" if jd_match.role_match else "❌"
            st.metric("Role match", role_label)

    # Top gaps
    if jd_match.top_gaps:
        st.markdown("**🚨 Top gaps** (required skills missing from CV)")
        gap_text = ", ".join(f"`{g}`" for g in jd_match.top_gaps)
        st.markdown(gap_text)

    # Matched skills (collapsed by default to keep UI clean)
    if jd_match.required_matched_list:
        with st.expander(f"✅ Matched required skills ({len(jd_match.required_matched_list)})"):
            for skill in jd_match.required_matched_list:
                locs = jd_match.section_distribution.get(skill, [])
                sec_names = ", ".join(loc.section for loc in locs) or "—"
                st.markdown(f"- **{skill}** — found in: {sec_names}")


def render_summary(summary: str) -> None:
    st.subheader("Executive Summary")
    st.info(summary)


def save_report(report, feedback: Dict[str, str], summary: str, pdf_name: str) -> Path:
    out_dir = Path(tempfile.mkdtemp(prefix="cv_review_"))
    payload = {
        "file": pdf_name,
        "overall": report.overall,
        "grade": report.grade,
        "summary": summary,
        "role": report.role,
        "role_confidence": report.role_confidence,
        "sections": {
            name: {
                "score": s.score,
                "evidence": s.evidence,
                "issues": s.issues,
                "feedback": feedback.get(name, ""),
            }
            for name, s in report.sections.items()
        },
    }
    out_file = out_dir / f"{Path(pdf_name).stem}_review.json"
    out_file.write_text(json.dumps(payload, indent=2))
    return out_file# --------------------------------------------------------------------------- #
# Main flow
# --------------------------------------------------------------------------- #
uploaded = st.file_uploader(
    "Upload CV (PDF or DOCX)",
    type=["pdf", "docx"],
)

if uploaded is None:
    st.info("👆 Upload a CV to begin. Try one of your own first — the model is small.")
    st.stop()

# Optional Job Description input (P1.2)
jd_text = st.text_area(
    "📋 Optional: paste a Job Description to match against",
    height=180,
    placeholder=(
        "Paste the full JD here. Include a 'Requirements' or 'Qualifications' "
        "section for best results — the matcher pulls required skills from there."
    ),
)
use_jd = bool(jd_text.strip())

# Save upload to a temp file (PyMuPDF needs a path).
suffix = ".pdf" if uploaded.name.lower().endswith(".pdf") else ".docx"
with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tf:
    tf.write(uploaded.read())
    cv_path = tf.name

try:
    with st.spinner("Parsing & scoring…"):
        # Translate UI "auto" → None (lets score_cv auto-detect).
        # Otherwise pass the explicit role through.
        role_arg = None if role_pref == "auto" else role_pref
        report = score_cv(cv_path, jd_text=jd_text if use_jd else None, role=role_arg)

    # Per-section LLM feedback runs concurrently (P1.3). Show progress
    # in the spinner as each section completes.
    progress_bar = st.progress(0.0, text="Generating LLM feedback…")
    sections_total = len(report.sections)

    def _on_section_done(name: str, completed: int, total: int) -> None:
        progress_bar.progress(
            completed / total,
            text=f"🤖 {name} done ({completed}/{total})",
        )

    # Language: optional override from UI; else auto-detect from CV.
    feedback = generate_feedback(
        report,
        progress_cb=_on_section_done,
        language=language_pref if language_pref != "auto" else None,
    )
    summary = generate_overall_summary(report, feedback)
    progress_bar.empty()

    render_score_card(report)
    if report.jd_match is not None:
        render_jd_match(report.jd_match)
    render_summary(summary)

    st.divider()
    st.subheader("Section Scores")
    for name, section in report.sections.items():
        render_section(name, section, feedback.get(name))

    # Download
    out_file = save_report(report, feedback, summary, uploaded.name)
    with open(out_file, "rb") as f:
        st.download_button(
            "⬇️ Download full review (JSON)",
            data=f.read(),
            file_name=out_file.name,
            mime="application/json",
        )

except Exception as e:
    st.error(f"Failed to review CV: {e}")
    st.exception(e)
finally:
    Path(cv_path).unlink(missing_ok=True)